### ISSUE TITLE
Legacy Change Heading icons?

### ISSUE THREAD

**Issue by dougmassay** [Sigil-Ebook/IconThemes#3]
I'm not quite sure what's going on, but the change heading icons (on the flyout menu of the QToolButton) seem fairly unusable on Windows and Linux. It doesn't matter whether I'm using darkmode or lightmode. They all appear with a totally black background and I can't read the lettering unless I get up close and really squint at the screen. But they don't seem to have a black background when I look at the icons in the repository itself.

The Change Case icons don't seem to suffer from the same issue. In fact, they seem completely inverted from the change heading icons.

**Comment by BeckyDTP** [comment]
I already sent a revised version (along with other corrections) to KevinH.

**Comment by kevinhendricks** [comment]
That is top of my to-do list for today.  I will grab BeckyEbook's new icons and get everything properly updated this afternoon if not sooner.

**Comment by kevinhendricks** [comment]
Okay, pushed all BeckyEbook's tweaked and fixed icons to both Sigil  (main and material) and IconThemes (main, material, and legacy).  Tagged the new IconThemes with 2020-10-14-1.  So hopefully soon we will have a tentative release built version of legacy we can confirm the fix with and close this.

**Comment by kevinhendricks** [comment]
Okay, I can confirm the fix for lagacy headings icons works on macOSX but I had to generate my own rcc file as I seemed to have confused AppyVeyor and somehow got a job queued for the last 25 minutes with no changes.

Not sure how I did that.  I did push all the changes and then pushed a new tag but I probably messed up.

@dougmassay, when you get a free moment, would you take a look at appveryor on IconThemes and let me know how I managed to get it queued but not actually run?

**Comment by dougmassay** [comment]
Not sure what the problem might have been, but it seems to have sorted itself. The new draft release was created with all of the assets.

**Comment by dougmassay** [comment]
It all looks good. Thanks! I'm going to go ahead and close this issue. Feel to update the 2020-10-14-1 release notes and publish if you like. Or I can do it later on if need be.

**Comment by kevinhendricks** [comment]
I added a release note and published it.
Thanks!
